Repository Team-Growthook/Growthook-AOS, pull requests merged in 2023-12, with the labels that each got.

#19 [REFACTOR] 바뀐 디자인 반영
  app/src/main/AndroidManifest.xml
  app/src/main/ic_growthook-playstore.png
  app/src/main/java/com/growthook/aos/presentation/home/CaveAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/util/EmptyDataObserver.kt
  app/src/main/res/drawable/ic_actionlist.xml
  app/src/main/res/drawable/ic_add_cave.xml
  app/src/main/res/drawable/ic_empty_insight.xml
  app/src/main/res/drawable/ic_growthook_foreground.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_cave.png
  app/src/main/res/drawable/ic_home_cave_night.xml
  app/src/main/res/drawable/ic_home_cave_pink.xml
  app/src/main/res/drawable/ic_home_cave_sunrise.xml
  app/src/main/res/drawable/ic_home_cave_sunset.xml
  app/src/main/res/drawable/ic_home_scrap_false.xml
  app/src/main/res/drawable/ic_home_scrap_true.xml
  app/src/main/res/drawable/ic_insght_no_action_no_scrap.xml
  app/src/main/res/drawable/ic_insight_no_action_yes_scrap.xml
  app/src/main/res/drawable/ic_insight_yes_action_no_scap.xml
  app/src/main/res/drawable/ic_insight_yes_action_yes_scrap.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_scrap_false.xml
  app/src/main/res/drawable/ic_scrap_selected.xml
  app/src/main/res/drawable/ic_scrap_true.xml
  app/src/main/res/drawable/ic_scrap_unselected.xml
  app/src/main/res/drawable/ic_scrap_yes_action_selected.xml
  app/src/main/res/drawable/ic_scrap_yes_action_unselected.xml
  app/src/main/res/drawable/ic_seed_selected.xml
  app/src/main/res/drawable/ic_seed_unselected.xml
  app/src/main/res/drawable/ic_temp_thook.png
  app/src/main/res/drawable/ic_thook.xml
  app/src/main/res/drawable/img_home_add_cave.png
  app/src/main/res/drawable/img_thook.png
  app/src/main/res/drawable/rect_gray700_gradient_0.xml
  app/src/main/res/drawable/sel_home_scrap.xml
  app/src/main/res/layout/activity_no_actionplan_insight.xml
  app/src/main/res/layout/dialog_right_intended.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_cave.xml
  app/src/main/res/layout/item_home_insight_lock.xml
  app/src/main/res/layout/item_home_insight_no_action.xml
  app/src/main/res/layout/item_home_insight_yes_action.xml
  app/src/main/res/mipmap-anydpi-v26/ic_growthook.xml
  app/src/main/res/mipmap-anydpi-v26/ic_growthook_round.xml
  app/src/main/res/mipmap-hdpi/ic_growthook.webp
  app/src/main/res/mipmap-hdpi/ic_growthook_round.webp
  app/src/main/res/mipmap-mdpi/ic_growthook.webp
  app/src/main/res/mipmap-mdpi/ic_growthook_round.webp
  app/src/main/res/mipmap-xhdpi/ic_growthook.webp
  app/src/main/res/mipmap-xhdpi/ic_growthook_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_growthook.webp
  app/src/main/res/mipmap-xxhdpi/ic_growthook_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_growthook.webp
  app/src/main/res/mipmap-xxxhdpi/ic_growthook_round.webp
  app/src/main/res/values/ic_growthook_background.xml
Labels: 💛 가은

#20 [FEAT] 보관함 상세 UI 및 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/data/datasource/local/TokenDataSource.kt
  app/src/main/java/com/growthook/aos/data/repository/TokenRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/di/DataStoreModule.kt
  app/src/main/java/com/growthook/aos/domain/usecase/local/PostUserUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailCaveSelectViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveModifySelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/util/extension/CommonTextWatcher.kt
  app/src/main/java/com/growthook/aos/util/extension/HideKeyboard.kt
  app/src/main/res/color/sel_cave_modify_btn.xml
  app/src/main/res/color/sel_textinput.xml
  app/src/main/res/drawable/ic_largethook_color.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_no_lock.xml
  app/src/main/res/drawable/ic_textinput_cancel.xml
  app/src/main/res/drawable/img_bear.png
  app/src/main/res/drawable/img_reward_thook.png
  app/src/main/res/layout/activity_cave_detail.xml
  app/src/main/res/layout/activity_cave_detail_modify.xml
  app/src/main/res/layout/dialog_single_intended.xml
  app/src/main/res/layout/fragment_cave_modify_select_bottomsheet.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/themes.xml
Labels: 💛 가은

#18 [FEAT] 보관함 생성뷰 UI/기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/storage/CreateStorageActivity.kt
  app/src/main/java/com/growthook/aos/presentation/storage/CreateStorageViewModel.kt
  app/src/main/res/drawable/ic_create_storage_clear.xml
  app/src/main/res/drawable/ic_create_storage_close.xml
  app/src/main/res/drawable/rect_gray400_fill_2.xml
  app/src/main/res/layout/activity_create_storage.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#26 [FEAT] 액션플랜 없는 인사이트 조회 UI 구현
  app/src/main/java/com/growthook/aos/domain/entity/Actionplan.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanViewModel.kt
  app/src/main/res/drawable/ic_collapse.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/rec_radius_bottom_10_gray600.xml
  app/src/main/res/layout/activity_add_actionplan.xml
  app/src/main/res/layout/item_actionplan_edittext.xml
Labels: ❤️ 지영

#31 [FEAT] 공통 bottomSheet 컴포넌트 구현
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailCaveSelectViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/home/CaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/base/BaseWritingBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/dialog/LeftIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/dialog/RightIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/dialog/SingleIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelect.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectAdapter.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt
  app/src/main/java/com/growthook/aos/util/writingbottomsheet/LargeWritingBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/writingbottomsheet/SmallWritingBottomSheet.kt
  app/src/main/res/color/sel_writing_save_btn.xml
  app/src/main/res/color/sel_writing_text.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/activity_create_storage.xml
  app/src/main/res/layout/fragment_large_writing_bottomsheet.xml
  app/src/main/res/layout/fragment_small_writing_bottomsheet.xml
  app/src/main/res/values/themes.xml
Labels: 💛 가은

#22 [ADD] 보관함 생성뷰 - 생성완료뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/model/NewCaveIntent.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/util/extension/Parcelable.kt
  app/src/main/res/drawable/sel_create_new_storage_btn.xml
  app/src/main/res/layout/activity_create_new_cave.xml
  app/src/main/res/layout/activity_create_storage.xml
  app/src/main/res/layout/activity_see_new_cave.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#33 [FEAT] 인사이트 작성 뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteCaveSelectAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteCaveSelectBottomSheetFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteGoalSelectBottomSheetFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
  app/src/main/java/com/growthook/aos/util/extension/AddSourceList.kt
  app/src/main/res/drawable/ic_drop_down.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/drawable/rect_gray200_botline_gray900_bot05.xml
  app/src/main/res/drawable/rect_gray200_botline_green200_bot05.xml
  app/src/main/res/drawable/sel_insight_write_btn_color.xml
  app/src/main/res/drawable/sel_insight_write_edt.xml
  app/src/main/res/layout/activity_insight_write.xml
  app/src/main/res/layout/fragment_insight_write_cave_select_bottomsheet.xml
  app/src/main/res/layout/fragment_insight_write_goal_select_bottomsheet.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💜 민정
