Repository Team-Growthook/Growthook-AOS, pull requests merged in 2024-03, with the labels that each got.

#107 [FEAT] 액션리스트 달성률 프로그래스바 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/presentation/MainActivity.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/ReviewDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/ReviewViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/TodolistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistViewModel.kt
  app/src/main/res/drawable/ic_progress_seed.xml
  app/src/main/res/drawable/linear_progrss_bar.xml
  app/src/main/res/drawable/rect_gray900_border_green600_fill_5.xml
  app/src/main/res/layout/activity_review_detail.xml
  app/src/main/res/layout/fragment_completed_actionlist.xml
  app/src/main/res/layout/fragment_proceeding_actionlist.xml
  app/src/main/res/layout/fragment_todolist.xml
Labels: ❤️ 지영

#112 [FIX] UX 라이팅 수정
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/DescAdapter.kt
  app/src/main/res/drawable/ic_onboarding_desc1.xml
  app/src/main/res/drawable/ic_onboarding_desc2.xml
  app/src/main/res/drawable/ic_onboarding_desc3.xml
  app/src/main/res/drawable/ic_onboarding_desc4.xml
  app/src/main/res/layout/fragment_desc.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_small_writing_bottomsheet.xml
Labels: 💛 가은

#113 [FEAT] 동굴 엠티 뷰 플로우 추가
  app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt
  app/src/main/res/drawable/ic_circle_plus.xml
  app/src/main/res/layout/fragment_cave_select_bottomsheet.xml
Labels: 💜 민정

#115 [FEAT] 인사이트 출처 관련 수정
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
  app/src/main/res/drawable/rect_red200_line_05.xml
  app/src/main/res/layout/activity_insight_write.xml
  app/src/main/res/layout/activity_insight_write_new.xml
  app/src/main/res/layout/activity_no_actionplan_insight.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#117 [FEAT] 보관함 생성 이후 공개/비공개 팝업 노출
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/res/layout/activity_see_new_cave.xml
Labels: 💜 민정

#120 [FEAT] 삭제한 할일 뒤로가기시 반영
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistFragment.kt
Labels: ❤️ 지영

#123 [FIX] 할일뷰 qa 반영
  app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/res/layout/item_completed_actionplan.xml
  app/src/main/res/layout/item_proceeding_actionplan.xml
Labels: ❤️ 지영

#124 [FIX] 인사이트 출처 유효하지 않을 경우 등록 안되도록 수정
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
Labels: 💜 민정

#128 [FIX] 할일뷰 QA 반영
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/TodolistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/TodolistViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/util/writingbottomsheet/LargeWritingBottomSheet.kt
  app/src/main/res/color/sel_textinput.xml
  app/src/main/res/layout/fragment_large_writing_bottomsheet.xml
  app/src/main/res/layout/fragment_small_writing_bottomsheet.xml
  app/src/main/res/layout/item_completed_actionplan.xml
  app/src/main/res/layout/item_proceeding_actionplan.xml
  app/src/main/res/values/themes.xml
Labels: ❤️ 지영

#127 [FIX] QA 반영
  app/build.gradle
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/DescAdapter.kt
  app/src/main/res/drawable/bg_home_insight_lock.xml
  app/src/main/res/drawable/ic_onboarding_desc1.xml
  app/src/main/res/drawable/ic_onboarding_desc2.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_desc_explain.xml
  app/src/main/res/layout/item_home_insight_lock.xml
Labels: 💛 가은

#130 [FIX] 할 일 완료 목록 btn 색상 수정
  app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistAdapter.kt
Labels: ❤️ 지영

#132 [FIX] 디자인QA 반영
  app/src/main/java/com/growthook/aos/presentation/onboarding/WhatDifficultFragment.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectAdapter.kt
  app/src/main/res/layout/item_home_cave.xml
Labels: 💛 가은
