Repository Team-Growthook/Growthook-AOS, pull requests merged in 2024-01, with the labels that each got.

#39 [FEAT] 홈/보관함 상세 api 연결
  app/build.gradle
  app/src/main/java/com/growthook/aos/App.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/CaveDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/CaveDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/entity/User.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestCaveModifyDto.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestSeedMoveDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetCavesDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetDetailCaveDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseMoveSeedDto.kt
  app/src/main/java/com/growthook/aos/data/repository/CaveRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/CaveService.kt
  app/src/main/java/com/growthook/aos/data/service/SeedService.kt
  app/src/main/java/com/growthook/aos/di/ApiModule.kt
  app/src/main/java/com/growthook/aos/di/DataSourceModule.kt
  app/src/main/java/com/growthook/aos/di/RepositoryModule.kt
  app/src/main/java/com/growthook/aos/di/RetrofitModule.kt
  app/src/main/java/com/growthook/aos/domain/entity/CaveDetail.kt
  app/src/main/java/com/growthook/aos/domain/repository/CaveRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/InsightRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/UserRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/DeleteSeedUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/GetCavesUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/MoveSeedUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/DeleteCaveUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/GetCaveDetailUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/ModifyCaveUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/local/PostUserUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailDeleteAlert.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveModifySelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/model/CaveModifyIntent.kt
  app/src/main/java/com/growthook/aos/presentation/model/NewCaveIntent.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginViewModel.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelect.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt
  app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt
Labels: 💛 가은

#37 [FEAT] 액션플랜 없는 인사이트 조회 뷰 - 수정
  app/src/main/java/com/growthook/aos/domain/entity/SeedInfo.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/model/SeedModifyIntent.kt
  app/src/main/res/layout/activity_seed_modify.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#42 [ADD] empty 뷰 추가
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/util/EmptyDataObserver.kt
  app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt
  app/src/main/res/drawable/ic_empty_cave.xml
  app/src/main/res/layout/fragment_cave_select_bottomsheet.xml
Labels: 💛 가은

#43 [FEAT] 보관함 생성 API 연결
  app/src/main/java/com/growthook/aos/data/datasource/remote/CaveDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/CaveDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestCavePostDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponsePostCaveDto.kt
  app/src/main/java/com/growthook/aos/data/repository/CaveRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/CaveService.kt
  app/src/main/java/com/growthook/aos/domain/repository/CaveRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/PostCaveUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveViewModel.kt
  app/src/main/res/layout/activity_create_new_cave.xml
  app/src/main/res/layout/activity_see_new_cave.xml
Labels: 💜 민정

#45 [FEAT] 인사이트 작성 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestSeedPostDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponsePostSeedDto.kt
  app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/SeedService.kt
  app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/seeddetail/PostSeedUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteCaveSelectAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteCaveSelectBottomSheetFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
  app/src/main/java/com/growthook/aos/util/dialog/SingleIntendedAlertDialog.kt
  app/src/main/res/layout/activity_insight_write.xml
  app/src/main/res/layout/activity_insight_write_new.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_insight_write_cave_select_bottomsheet.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#47 [FEAT] 온보딩 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/data/entity/User.kt
  app/src/main/java/com/growthook/aos/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/domain/entity/Explain.kt
  app/src/main/java/com/growthook/aos/domain/repository/UserRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/local/PostUserUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/DescAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/DescFragment.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/SolutionFragment.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/SplashActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/SplashViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/WhatDifficultFragment.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/WhatDifficultViewModel.kt
  app/src/main/res/anim/anim_fade_out.xml
  app/src/main/res/anim/anim_slide_in_from_left_fade_in.xml
  app/src/main/res/anim/anim_slide_in_from_right_fade_in.xml
  app/src/main/res/color/sel_btn.xml
  app/src/main/res/color/sel_text.xml
  app/src/main/res/drawable/bg_splash_cave.xml
  app/src/main/res/drawable/circle_gray300_fill_0.xml
  app/src/main/res/drawable/circle_white000_fill_0.xml
  app/src/main/res/drawable/ic_dont.xml
  app/src/main/res/drawable/ic_forget.xml
  app/src/main/res/drawable/ic_growthook_login.xml
  app/src/main/res/drawable/ic_growthook_logo.xml
  app/src/main/res/drawable/ic_notfound.xml
  app/src/main/res/drawable/ic_onboarding_desc1.xml
  app/src/main/res/drawable/ic_onboarding_desc2.xml
  app/src/main/res/drawable/ic_onboarding_desc3.xml
  app/src/main/res/drawable/ic_onboarding_desc4.xml
  app/src/main/res/drawable/ic_sad.xml
  app/src/main/res/drawable/img_onboarding_kakao_login.png
  app/src/main/res/drawable/img_onboarding_login.png
  app/src/main/res/drawable/rect_gray400_fill_10.xml
  app/src/main/res/drawable/rect_gray500_line_10.xml
  app/src/main/res/drawable/sel_onboarding_indicator.xml
  app/src/main/res/layout/activity_cave_detail_modify.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_desc.xml
  app/src/main/res/layout/fragment_large_writing_bottomsheet.xml
  app/src/main/res/layout/fragment_small_writing_bottomsheet.xml
  app/src/main/res/layout/fragment_solution.xml
  app/src/main/res/layout/fragment_what_difficult.xml
  app/src/main/res/layout/item_desc_explain.xml
  app/src/main/res/values/themes.xml
Labels: 💛 가은

#48 [FIX] 기타 에러 수정 및 이미지 교체
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailDeleteAlert.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginViewModel.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelect.kt
  app/src/main/res/drawable/bg_splash_cave.xml
  app/src/main/res/drawable/ic_cave_plus.xml
  app/src/main/res/drawable/ic_home_add_cave.xml
  app/src/main/res/drawable/ic_home_cave_night.xml
  app/src/main/res/drawable/ic_home_cave_pink.xml
  app/src/main/res/drawable/ic_home_cave_sunrise.xml
  app/src/main/res/drawable/ic_home_cave_sunset.xml
  app/src/main/res/drawable/img_home_add_cave.png
  app/src/main/res/layout/fragment_home.xml
Labels: 💛 가은

#54 [FEAT] 새로 배포된 씨앗 api 연결 구현
  app/src/main/java/com/growthook/aos/data/datasource/remote/CaveDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/CaveDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseAlarmDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetCaveSeedsDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetSeedsDto.kt
  app/src/main/java/com/growthook/aos/data/repository/CaveRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/CaveService.kt
  app/src/main/java/com/growthook/aos/data/service/SeedService.kt
  app/src/main/java/com/growthook/aos/domain/entity/Insight.kt
  app/src/main/java/com/growthook/aos/domain/repository/CaveRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/ScrapSeedUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/UnLockSeedUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/GetCaveSeedsUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/home/GetSeedAlarmUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/home/GetSeedsUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt
Labels: 💛 가은

#57 [FEAT] member api 구현
  app/src/main/java/com/growthook/aos/data/datasource/remote/MemberDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/MemberDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGatheredThookDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetProfileDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetUsedThook.kt
  app/src/main/java/com/growthook/aos/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/MemberService.kt
  app/src/main/java/com/growthook/aos/di/ApiModule.kt
  app/src/main/java/com/growthook/aos/di/DataSourceModule.kt
  app/src/main/java/com/growthook/aos/di/RepositoryModule.kt
  app/src/main/java/com/growthook/aos/domain/repository/MemberRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/GetGatherdThookUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/mypage/DeleteMemberUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/mypage/GetEmailUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/mypage/GetUsedThookUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageActivity.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: 💛 가은

#60 [FEAT] 인사이트 조회 (액션 플랜 X) - 수정 서버 통신
  app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestSeedModifyDto.kt
  app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/SeedService.kt
  app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/seeddetail/ModifySeedUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt
  app/src/main/res/layout/activity_seed_modify.xml
Labels: 💜 민정

#64 [FEAT] 소셜로그인 api & 토큰 재발급 api 구현
  app/build.gradle
  app/src/main/java/com/growthook/aos/data/datasource/remote/RefreshDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/SignUpDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/RefreshDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SignUpDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/request/RequestPostAuthDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponsePostAuthDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseRefreshTokenDto.kt
  app/src/main/java/com/growthook/aos/data/repository/RefreshRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/TokenRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/RefreshService.kt
  app/src/main/java/com/growthook/aos/data/service/SignUpService.kt
  app/src/main/java/com/growthook/aos/di/ApiModule.kt
  app/src/main/java/com/growthook/aos/di/DataSourceModule.kt
  app/src/main/java/com/growthook/aos/di/Qualifier.kt
  app/src/main/java/com/growthook/aos/di/RefreshRetrofitModule.kt
  app/src/main/java/com/growthook/aos/di/RepositoryModule.kt
  app/src/main/java/com/growthook/aos/di/RetrofitModule.kt
  app/src/main/java/com/growthook/aos/di/SignUpRetrofitModule.kt
  app/src/main/java/com/growthook/aos/domain/repository/RefreshRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/SignUpRepository.kt
  app/src/main/java/com/growthook/aos/domain/repository/TokenRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/local/PostTokenUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/onboarding/SignUpUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginViewModel.kt
Labels: 💛 가은

#69 [FEAT] 수정된 api 반영 & 뷰 연결 구현
  app/src/main/java/com/growthook/aos/data/datasource/remote/CaveDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/CaveDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/entity/User.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponsePostCaveDto.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponsePostSeedDto.kt
  app/src/main/java/com/growthook/aos/data/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/CaveService.kt
  app/src/main/java/com/growthook/aos/data/service/SeedService.kt
  app/src/main/java/com/growthook/aos/di/RefreshRetrofitModule.kt
  app/src/main/java/com/growthook/aos/di/RetrofitModule.kt
  app/src/main/java/com/growthook/aos/domain/entity/SeedInfo.kt
  app/src/main/java/com/growthook/aos/domain/repository/UserRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/local/PostUserUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/MainActivity.kt
  app/src/main/java/com/growthook/aos/presentation/MainActivityViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/model/SeedModifyIntent.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/LoginActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/SplashActivity.kt
  app/src/main/java/com/growthook/aos/presentation/onboarding/SplashViewModel.kt
  app/src/main/java/com/growthook/aos/util/EmptyDataObserver.kt
  app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt
  app/src/main/res/layout/activity_cave_detail.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 💛 가은

#73 [FIX] 인사이트 작성 연결 안된 부분 구현
  app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
Labels: 💜 민정

#76 [FEAT] 액션리스트 스크랩 기능 추가
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt
  app/src/main/res/drawable/rect_gray600_fill_5.xml
  app/src/main/res/layout/fragment_completed_actionlist.xml
  app/src/main/res/layout/item_completed_actionplan.xml
Labels: ❤️ 지영

#77 [FIX] QA에 따른 뷰 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/growthook/aos/App.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/MemberDataSource.kt
  app/src/main/java/com/growthook/aos/data/datasource/remote/impl/MemberDataSourceImpl.kt
  app/src/main/java/com/growthook/aos/data/model/response/ResponseGetProfileDto.kt
  app/src/main/java/com/growthook/aos/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/growthook/aos/data/service/MemberService.kt
  app/src/main/java/com/growthook/aos/domain/entity/Profile.kt
  app/src/main/java/com/growthook/aos/domain/repository/MemberRepository.kt
  app/src/main/java/com/growthook/aos/domain/usecase/mypage/GetEmailUseCase.kt
  app/src/main/java/com/growthook/aos/domain/usecase/mypage/GetProfileUseCase.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageViewModel.kt
  app/src/main/java/com/growthook/aos/util/GlideModule.kt
  app/src/main/res/drawable/ic_profile_default.xml
  app/src/main/res/layout/activity_cave_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/themes.xml
Labels: 💛 가은

#78 [FIX] Base dialog 수정
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageActivity.kt
  app/src/main/java/com/growthook/aos/util/base/BaseAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/dialog/LeftIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/dialog/RightIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/dialog/SingleIntendedAlertDialog.kt
  app/src/main/res/layout/dialog_right_intended.xml
Labels: ❤️ 지영

#81 [FIX] 기획 수정 반영
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageActivity.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageViewModel.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_kakao_icon.xml
  app/src/main/res/drawable/img_bear.png
  app/src/main/res/drawable/img_onboarding_kakao_login.png
  app/src/main/res/layout/activity_detail_my_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_see_new_cave.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 💛 가은

#85 [FIX] 인사이트 조회 -> 액션리스트 스크랩 반영
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt
Labels: ❤️ 지영

#89 [FIX] QA 수정 반영
  app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageActivity.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt
  app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt
  app/src/main/res/layout/fragment_cave_select_bottomsheet.xml
  app/src/main/res/layout/fragment_large_writing_bottomsheet.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_small_writing_bottomsheet.xml
Labels: 💛 가은

#90 [REFACTOR] setOnSingleClickListener
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveModifySelectBottomSheet.kt
  app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/home/CaveAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/add/AddActionplanActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt
  app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/growthook/aos/util/OnSingleClickListener.kt
  app/src/main/java/com/growthook/aos/util/extension/ViewExt.kt
Labels: 💛 가은

#91 [QA] 최종 QA 반영
  app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt
  app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt
  app/src/main/res/layout/activity_no_actionplan_insight.xml
Labels: ❤️ 지영

#92 [FIX] QA 수정
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt
  app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt
  app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt
  app/src/main/java/com/growthook/aos/util/dialog/SingleIntendedAlertDialog.kt
  app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt
  app/src/main/res/color/sel_cave_create_btn.xml
  app/src/main/res/layout/activity_create_new_cave.xml
  app/src/main/res/layout/activity_insight_write.xml
  app/src/main/res/values/strings.xml
Labels: 💜 민정

#96 [QA] QA 반영
  app/src/main/res/layout/activity_insight_write.xml
  app/src/main/res/layout/activity_insight_write_new.xml
  app/src/main/res/layout/activity_no_actionplan_insight.xml
  app/src/main/res/layout/activity_see_new_cave.xml
  app/src/main/res/layout/activity_seed_modify.xml
Labels: 💜 민정
